import type { Scenario } from './types';

export const SCENARIOS: Scenario[] = [
  {
    id: 'A',
    label: 'Scenario A (High Risk)',
    description: 'Child age 13 attempting a large transaction on Roblox late at night.',
    request: {
      id: 'tx_req_001',
      childName: 'Aarav Sharma',
      childAge: 13,
      gameName: 'Roblox',
      itemName: '4,500 Robux Deluxe Pack',
      purchaseAmount: 4999,
      requestTime: '11:42 PM',
      riskLevel: 'High',
      riskScore: 91,
      explanation: 'This purchase is 12x larger than the child\'s average historical transaction (₹400) and was initiated late at night (11:42 PM). Additionally, age verification estimates the user is 13, which carries higher risk for unsanctioned card usage.',
      recommendation: 'Reject',
      riskBreakdown: {
        age: 88,
        amount: 95,
        frequency: 82,
        pattern: 96,
        time: 92,
      },
    },
  },
  {
    id: 'B',
    label: 'Scenario B (Medium Risk)',
    description: 'Teenager age 16 buying a battle pass on BGMI with minor microtransaction spam.',
    request: {
      id: 'tx_req_002',
      childName: 'Riya Verma',
      childAge: 16,
      gameName: 'BGMI (Battlegrounds Mobile India)',
      itemName: 'Elite Royale Pass + 60 UC',
      purchaseAmount: 199,
      requestTime: '04:15 PM',
      riskLevel: 'Medium',
      riskScore: 42,
      recommendation: 'Review Carefully',
      explanation: 'While the purchase amount is low (₹199), the user has made 5 purchases in the last 48 hours, suggesting a potential impulsive buying streak. Age estimated is 16. Monitor spending patterns closely.',
      riskBreakdown: {
        age: 45,
        amount: 15,
        frequency: 72,
        pattern: 50,
        time: 25,
      },
    },
  },
  {
    id: 'C',
    label: 'Scenario C (Low Risk)',
    description: 'Adult user age 24 buying Minecraft content during daytime hours.',
    request: {
      id: 'tx_req_003',
      childName: 'Kabir Sen',
      childAge: 24,
      gameName: 'Minecraft',
      itemName: 'Minecraft Starter Collection',
      purchaseAmount: 299,
      requestTime: '02:30 PM',
      riskLevel: 'Low',
      riskScore: 12,
      recommendation: 'Approve',
      explanation: 'The user is verified to be 24 years old (legal adult). The transaction amount (₹299) is fully aligned with standard account usage, initiated during regular afternoon hours, and carries low overall profile risk.',
      riskBreakdown: {
        age: 5,
        amount: 12,
        frequency: 10,
        pattern: 18,
        time: 15,
      },
    },
  },
];
